### ISSUE TITLE
Unable to run script past login

### ISSUE THREAD

**Issue by Enzemo** [TheNetsky/Microsoft-Rewards-Script#1]
Below is my terminal output after running. It crashes after successfully logging in and refreshing the page

PS C:\Users\Enzemo\Downloads\Microsoft-Rewards-Script-main> npm run start

```
> microsoft-rewards-script@1.0.4 start
> node ./dist/index.js

[2023-10-01T15:53:58.461Z] [LOG] [MAIN] Bot started
[2023-10-01T15:53:58.462Z] [LOG] [MAIN] Started tasks for account xxxxxxxx@outlook.com
[2023-10-01T15:53:59.163Z] [LOG] [MAIN] Starting DESKTOP browser
[2023-10-01T15:54:00.978Z] [LOG] [LOGIN] Already logged in
[2023-10-01T15:54:00.978Z] [LOG] [LOGIN-BING] Verifying Bing login
[2023-10-01T15:54:05.333Z] [LOG] [LOGIN-BING] Bing login verification passed!
[2023-10-01T15:54:05.333Z] [LOG] [LOGIN] Logged in successfully
[2023-10-01T15:54:16.591Z] [LOG] [MAIN-POINTS] Current point count: 0
C:\Users\Enzemo\Downloads\Microsoft-Rewards-Script-main\dist\BrowserFunc.js:127
    data.userStatus.counters.mobileSearch.forEach(x => totalEarnablePoints += (x.pointProgressMax - x.pointProgress));
                                          ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at getEarnablePoints (C:\Users\Enzemo\Downloads\Microsoft-Rewards-Script-main\dist\BrowserFunc.js:127:43)
    at Desktop (C:\Users\Enzemo\Downloads\Microsoft-Rewards-Script-main\dist\index.js:48:70)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (C:\Users\Enzemo\Downloads\Microsoft-Rewards-Script-main\dist\index.js:21:9)

Node.js v18.18.0
PS C:\Users\Enzemo\Downloads\Microsoft-Rewards-Script-main>
```

**Comment by TheNetsky** [comment]
I'll check it out later, I've only used an account that has points and is in my country. Not sure what country you're from.

Rewards/task differ heavily per country.

**Comment by Enzemo** [comment]
Ah. sorry, I'm in the UK. I've also tried redeeming a reward so it had more than zero points but it still persists

**Comment by TheNetsky** [comment]
Likely that the script is different on your end. I'll try n see if I can replicate, however I've used it this morning fine.

**Comment by Enzemo** [comment]
I'm unsure why that would be the case, I just cloned it from the github and built following the instructions. Would posting my config help?

```
{
    "baseURL": "https://rewards.bing.com",
    "sessionPath": "sessions",
    "headless": false,
    "runOnZeroPoints": true,
    "searches": {
        "doMobile": true,
        "doDesktop": true,
        "scrollRandomResults": true,
        "clickRandomResults": true
    },
    "webhook": {
        "enabled": false,
        "url": ""
    }
}{
    "baseURL": "https://rewards.bing.com",
    "sessionPath": "sessions",
    "headless": false,
    "runOnZeroPoints": true,
    "searches": {
        "doMobile": true,
        "doDesktop": true,
        "scrollRandomResults": true,
        "clickRandomResults": true
    },
    "webhook": {
        "enabled": false,
        "url": ""
    }
}
```

**Comment by TheNetsky** [comment]
Already found the issue, will fix it tomorrow.

**Comment by Enzemo** [comment]
Fantastic, thanks so much

**Comment by TheNetsky** [comment]
Should be fixed now, redownload the script and re-install all packages.

**Comment by TheNetsky** [comment]
Are your issues resolved?

**Comment by Enzemo** [comment]
Yes thanks very much
