### ISSUE TITLE
Invalid URL error

### ISSUE THREAD

**Issue by XRominjol** [TheNetsky/Microsoft-Rewards-Script#119]
Idk whats wrong, but i caught this error:

PS C:\Users\Администратор\Desktop\Microsoft-Rewards-Script-main> npm run start

> microsoft-rewards-script@1.4.7 start
> node ./dist/index.js

[16.06.2024, 01:05:18] [PID: 6860] [LOG] [MAIN] Bot started with 1 clusters
[16.06.2024, 01:05:18] [PID: 6860] [LOG] [MAIN-WORKER] Started tasks for account *******@outlook.com
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserType.launch: Invalid URL
    at Browser.createBrowser (C:\Users\Администратор\Desktop\Microsoft-Rewards-Script-main\dist\browser\Browser.js:20:61)
    at MicrosoftRewardsBot.Desktop (C:\Users\Администратор\Desktop\Microsoft-Rewards-Script-main\dist\index.js:99:51)
    at MicrosoftRewardsBot.runTasks (C:\Users\Администратор\Desktop\Microsoft-Rewards-Script-main\dist\index.js:83:24)
    at MicrosoftRewardsBot.run (C:\Users\Администратор\Desktop\Microsoft-Rewards-Script-main\dist\index.js:51:18)
    at C:\Users\Администратор\Desktop\Microsoft-Rewards-Script-main\dist\index.js:197:9 {
  name: 'TypeError'
}

Node.js v20.14.0

**Comment by TheNetsky** [comment]
Did you enter a proxy?

**Comment by XRominjol** [comment]
Yes, im entered proxy.

My accounts list:

[
    {
        "email": "*****@outlook.com",
        "password": "******",
        "proxy": {
            "url": ":79.***.***.***",
            "port": 3328,
            "username": "*****",
            "password": "******"
        }
    }
]

**Comment by TheNetsky** [comment]
add http:// or https:// to the proxy ip

**Comment by XRominjol** [comment]
thx a lot

**Comment by DestroyerV** [comment]
> thx a lot

Which proxy service are you using?
