### ISSUE TITLE
1.5 Fails to run with more than one cluster if parallel is set to false

### ISSUE THREAD

**Issue by AKH1701** [TheNetsky/Microsoft-Rewards-Script#180]
Error (2 clusters):
```
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: setRawMode EIO
    at ReadStream.setRawMode (node:tty:77:31)
    at [_setRawMode] [as _setRawMode] (node:internal/readline/interface:381:18)
    at Interface.InterfaceConstructor (node:internal/readline/interface:317:22)
    at new Interface (node:readline:114:3)
    at Object.createInterface (node:readline:213:10)
    at Object.<anonymous> (/home/akh/Microsoft-Rewards-Script/dist/functions/Login.js:33:31)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
Emitted 'error' event on Interface instance at:
    at ReadStream.onerror (node:internal/readline/interface:246:10)
    at ReadStream.emit (node:events:517:28)
    at ReadStream.setRawMode (node:tty:77:10)
    at [_setRawMode] [as _setRawMode] (node:internal/readline/interface:381:18)
    [... lines matching original stack trace ...]
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10) {
  errno: -5,
  code: 'EIO',
  syscall: 'setRawMode'
}

Node.js v18.19.1
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: setRawMode EIO
    at ReadStream.setRawMode (node:tty:77:31)
    at [_setRawMode] [as _setRawMode] (node:internal/readline/interface:381:18)
    at Interface.InterfaceConstructor (node:internal/readline/interface:317:22)
    at new Interface (node:readline:114:3)
    at Object.createInterface (node:readline:213:10)
    at Object.<anonymous> (/home/akh/Microsoft-Rewards-Script/dist/functions/Login.js:33:31)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
Emitted 'error' event on Interface instance at:
    at ReadStream.onerror (node:internal/readline/interface:246:10)
    at ReadStream.emit (node:events:517:28)
    at ReadStream.setRawMode (node:tty:77:10)
    at [_setRawMode] [as _setRawMode] (node:internal/readline/interface:381:18)
    [... lines matching original stack trace ...]
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10) {
  errno: -5,
  code: 'EIO',
  syscall: 'setRawMode'
}

Node.js v18.19.1
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: setRawMode EIO
    at ReadStream.setRawMode (node:tty:77:31)
    at [_setRawMode] [as _setRawMode] (node:internal/readline/interface:381:18)
    at Interface.InterfaceConstructor (node:internal/readline/interface:317:22)
    at new Interface (node:readline:114:3)
    at Object.createInterface (node:readline:213:10)
    at Object.<anonymous> (/home/akh/Microsoft-Rewards-Script/dist/functions/Login.js:33:31)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
Emitted 'error' event on Interface instance at:
    at ReadStream.onerror (node:internal/readline/interface:246:10)
    at ReadStream.emit (node:events:517:28)
    at ReadStream.setRawMode (node:tty:77:10)
    at [_setRawMode] [as _setRawMode] (node:internal/readline/interface:381:18)
    [... lines matching original stack trace ...]
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10) {
  errno: -5,
  code: 'EIO',
  syscall: 'setRawMode'
}

Node.js v18.19.1
node:events:495
      throw er; // Unhandled 'error' event
      ^

Error: setRawMode EIO
    at ReadStream.setRawMode (node:tty:77:31)
    at [_setRawMode] [as _setRawMode] (node:internal/readline/interface:381:18)
    at Interface.InterfaceConstructor (node:internal/readline/interface:317:22)
    at new Interface (node:readline:114:3)
    at Object.createInterface (node:readline:213:10)
    at Object.<anonymous> (/home/akh/Microsoft-Rewards-Script/dist/functions/Login.js:33:31)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
Emitted 'error' event on Interface instance at:
    at ReadStream.onerror (node:internal/readline/interface:246:10)
    at ReadStream.emit (node:events:517:28)
    at ReadStream.setRawMode (node:tty:77:10)
    at [_setRawMode] [as _setRawMode] (node:internal/readline/interface:381:18)
    [... lines matching original stack trace ...]
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10) {
  errno: -5,
  code: 'EIO',
  syscall: 'setRawMode'
}

Node.js v18.19.1
```

**Comment by TheNetsky** [comment]
I've not tested clustering yet

**Comment by AariaX** [comment]
https://github.com/AariaX/Microsoft-Rewards-Script/tree/cluster Just sharing my fix with you

**Comment by mgrimace** [comment]
> https://github.com/AariaX/Microsoft-Rewards-Script/tree/cluster Just sharing my fix with you

Thanks for this, I'm testing your fix now with docker. I ran into an issue which ended up not completing the searches for any accounts. I tested with cluster=2, parallel=true, and headless=true.

```bash
[1/26/2025, 10:40:28 AM] [PID: 198] [LOG] DESKTOP [SEARCH-BING] Starting Bing searches
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.reload: Page crashed
Call log:
  - waiting for navigation until "domcontentloaded"

    at BrowserFunc.getDashboardData (/usr/src/microsoft-rewards-script/dist/browser/BrowserFunc.js:70:33)
    at BrowserFunc.getSearchPoints (/usr/src/microsoft-rewards-script/dist/browser/BrowserFunc.js:98:42)
    at Search.doSearch (/usr/src/microsoft-rewards-script/dist/functions/activities/Search.js:15:58)
    at async Activities.doSearch (/usr/src/microsoft-rewards-script/dist/functions/Activities.js:16:13)
    at async MicrosoftRewardsBot.Desktop (/usr/src/microsoft-rewards-script/dist/index.js:134:13)
    at async MicrosoftRewardsBot.runTasks (/usr/src/microsoft-rewards-script/dist/index.js:86:13)
    at async process.<anonymous> (/usr/src/microsoft-rewards-script/dist/index.js:79:13) {
  name: 'Error'
}
```

and again for mobile,

```bash
[1/26/2025, 10:40:29 AM] [PID: 200] [LOG] MOBILE [PUNCH-CARD] All "Punch Card" items have been completed
[1/26/2025, 10:40:29 AM] [PID: 200] [LOG] MOBILE [SEARCH-BING] Starting Bing searches
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.reload: Page crashed
Call log:
  - waiting for navigation until "domcontentloaded"

    at BrowserFunc.getDashboardData (/usr/src/microsoft-rewards-script/dist/browser/BrowserFunc.js:70:33)
    at BrowserFunc.getSearchPoints (/usr/src/microsoft-rewards-script/dist/browser/BrowserFunc.js:98:42)
    at Search.doSearch (/usr/src/microsoft-rewards-script/dist/functions/activities/Search.js:15:58)
    at async Activities.doSearch (/usr/src/microsoft-rewards-script/dist/functions/Activities.js:16:13)
    at async MicrosoftRewardsBot.Desktop (/usr/src/microsoft-rewards-script/dist/index.js:134:13)
    at async MicrosoftRewardsBot.runTasks (/usr/src/microsoft-rewards-script/dist/index.js:86:13)
    at async process.<anonymous> (/usr/src/microsoft-rewards-script/dist/index.js:79:13) {
  name: 'Error'
}

Node.js v18.20.6
[1/26/2025, 10:40:30 AM] [PID: 42] [WARN] MAIN [MAIN-WORKER] Worker 200 destroyed | Code: 1 | Active workers: 0
```

**Comment by Slowlife01** [comment]
I'll see what I can do about that. And I've not tested it with parallel=true and that is definitely an issue

**Comment by AariaX** [comment]
I'll see what I can do about that. And I've not tested it with
parallel=true and that is definitely an issue

**Comment by AariaX** [comment]
I added support for parallel check it out. I tested it with your docker pr

**Comment by mgrimace** [comment]
> I added support for parallel check it out. I tested it with your docker pr

Preliminary testing is working!!! 
Docker1.5, headless=true, clusters=2 (with two accounts), parallel=true

Great work, I'll watch for a full period (many of my searches, etc., were all ready done why I tried it, but it's running as expected).

Seems to be doing desktop and mobile for 2 accounts simultaneously, brilliant

**Comment by TheNetsky** [comment]
> I added support for parallel check it out. I tested it with your docker pr

Want to PR? Else I'll just look at your code and implement it with an upcoming update I have going on,

**Comment by AariaX** [comment]
Feel free to include it in your upcoming update, as the fix was fairly
straightforward

**Comment by mgrimace** [comment]
> Feel free to include it in your upcoming update, as the fix was fairly
> straightforward
> […](#)

Ok, it ran as a full scheduled run today. The only issue I ran into was that one account, it error’d out after during the searches and stopped the account from the error. I’d expect it to timeout, then retry the search 1/5, 2/5… and so on, and continue. This may or may not be related to the fix, or just the script itself, and here’s the error details:

```bash
[1/28/2025, 9:00:55 AM] [PID: 1523] [WARN] MOBILE [SEARCH-BING] Retrying search, attempt 0/5
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goto: net::ERR_CONNECTION_CLOSED at https://www.bing.com/search?q=epicure&qs=n&form=QBRE&sp=-1&lq=0&pq=winnipeg%20jets&sc=12-13&sk=&cvid=E141CCE3A2AF441BBE9E2E9C01266BAF&ghsh=0&ghacc=0&ghpl=
Call log:
  - navigating to "https://www.bing.com/search?q=epicure&qs=n&form=QBRE&sp=-1&lq=0&pq=winnipeg%20jets&sc=12-13&sk=&cvid=E141CCE3A2AF441BBE9E2E9C01266BAF&ghsh=0&ghacc=0&ghpl=", waiting until "load"

    at Search.closeTabs (/usr/src/microsoft-rewards-script/dist/functions/activities/Search.js:271:27)
    at async Search.bingSearch (/usr/src/microsoft-rewards-script/dist/functions/activities/Search.js:152:17)
    at async Search.doSearch (/usr/src/microsoft-rewards-script/dist/functions/activities/Search.js:38:30)
    at async Activities.doSearch (/usr/src/microsoft-rewards-script/dist/functions/Activities.js:16:13)
    at async MicrosoftRewardsBot.Mobile (/usr/src/microsoft-rewards-script/dist/index.js:194:17)
    at async MicrosoftRewardsBot.runTasks (/usr/src/microsoft-rewards-script/dist/index.js:87:17)
    at async process.<anonymous> (/usr/src/microsoft-rewards-script/dist/index.js:79:13) {
  name: 'Error'
}

Node.js v18.20.6
[1/28/2025, 9:01:33 AM] [PID: 1516] [WARN] MAIN [MAIN-WORKER] Worker 1523 destroyed | Code: 1 | Active workers: 1
[1/28/2025, 9:01:34
```
In this case the other cluster/account continued just fine, and prior to this error both clustering and parallel were working as expected (e.g., both accounts running both desktop and mobile at the same time)

**Comment by mgrimace** [comment]
> Interesting, am not sure why it didn't continue... I assume there's not much before the logs you've posted?

Nothing but regular searches prior to the error:
```
[1/28/2025, 8:57:19 AM] [PID: 1524] [LOG] MOBILE [SEARCH-BING] 33 Points Remaining | Query: peavey mart
[1/28/2025, 8:57:47 AM] [PID: 1523] [LOG] MOBILE [SEARCH-BING] 36 Points Remaining | Query: epicure
[1/28/2025, 8:58:12 AM] [PID: 1523] [LOG] DESKTOP [SEARCH-BING] 45 Points Remaining | Query: amazon warehouses quebec
[1/28/2025, 8:59:43 AM] [PID: 1524] [LOG] DESKTOP [SEARCH-BING] 45 Points Remaining | Query: kobe bryant
[1/28/2025, 9:00:53 AM] [PID: 1523] [ERROR] MOBILE [SEARCH-BING] Search failed, An error occurred:TimeoutError: page.reload: Timeout 30000ms exceeded.
``

^^ which also shows the clustering and parallel

**Comment by TheNetsky** [comment]
Interesting, wondering why it errors with page.reload? The only reload it has is referring to "reloadBadPage" which if it errors there, should be caught and shown, which it is not? The other could be it errors at refreshing points.

**Comment by mgrimace** [comment]
Its also possibly unrelated to clustering or this fix, I often run the script a few times in the day just in case there's these kinds of quirks - sometimes its something on MS' end too. Either way when the script re-ran later there were no errors (it finished the previous searches).

**Comment by mgrimace** [comment]
Honestly too, kudos AariaX and Netsky, clusters + parallels is really incredible nicely done.

**Comment by TheNetsky** [comment]
I pinpointed the issue, currently looking to fix it.

**Comment by MacMarde** [comment]
Clustering is not working. I have tried with 2 accounts and set "clusters": 2 in the config.json
I did not change anything else in the bot besides accounts.json.

It is not working. Nothing happens. The script hangs without error or doing anything. I can also not debug with Visual Code, because pausing the script execution is not working.

All I see is this:

[9/12/2025, 7:24:20 PM] [PID: 6784] [LOG] MAIN [MAIN] Bot started with 2 clusters
Logger.ts:42
[9/12/2025, 7:24:20 PM] [PID: 6784] [LOG] MAIN [MAIN-PRIMARY] Primary process started

Nothing more is happening

As soon as I set "clusters" back to 1 in the config.json it is working again.

I have tried it with the latest source code available on github with Visual Code and did not change anything else.
