### ISSUE TITLE
Issue with doing punch cards

### ISSUE THREAD

**Issue by MintOcha** [TheNetsky/Microsoft-Rewards-Script#182]
This error pops up when attempting to solve punch cards. I am running the script on github codespaces in the US region
```
/workspaces/codespaces-blank/dist/functions/Workers.js:36
            this.bot.log('PUNCH-CARD', `Started solving "Punch Card" items for punchcard: "${punchCard.parentPromotion.title}"`);
                                                                                                                       ^

TypeError: Cannot read properties of null (reading 'title')
    at Workers.doPunchCard (/workspaces/codespaces-blank/dist/functions/Workers.js:36:120)
    at async MicrosoftRewardsBot.Desktop (/workspaces/codespaces-blank/dist/index.js:134:13)
    at async MicrosoftRewardsBot.runTasks (/workspaces/codespaces-blank/dist/index.js:84:13)

```

**Comment by TheNetsky** [comment]
Fixed in 1.5
