### ISSUE TITLE
pointProgressMax can't be read

### ISSUE THREAD

**Issue by kloklojul** [TheNetsky/Microsoft-Rewards-Script#22]
```
\Microsoft-Rewards-Script-main\dist\functions\activities\Search.js:26
            (edgeData.pointProgressMax - edgeData.pointProgress) + (genericData.pointProgressMax - genericData.pointProgress);
                      ^

TypeError: Cannot read properties of undefined (reading 'pointProgressMax')
```
when trying to calculate the left points the app breaks with the above message. I encapsulated the block with a try catch for the meantime. 
``` in Serach.ts
        let missingPoints = 0
        try{
        missingPoints = (this.bot.isMobile && mobileData) ?
            (mobileData.pointProgressMax - mobileData.pointProgress) :
            (edgeData.pointProgressMax - edgeData.pointProgress) + (genericData.pointProgressMax - genericData.pointProgress)
        }catch(error){
            this.bot.log('SEARCH-BING', 'Error getting point progress')
            missingPoints = 0
        }
        if (missingPoints == 0) {
            this.bot.log('SEARCH-BING', `Bing searches for ${this.bot.isMobile ? 'MOBILE' : 'DESKTOP'} have already been completed`)
            return
        }
```
I assume it's because there are not points left to gather.

**Comment by TheNetsky** [comment]
This is an issue I've personally have yet to encounter after using the script daily.

**Comment by PiporGames** [comment]
Got the same issue. However, I can still earn points, so I guess it isn't because of no points left to gather.

**Comment by mgrimace** [comment]
I obtained this error as part of my troubleshooting the error #18.

From that thread, I am also experiencing the `too early` error. To resolve it, I set `domorepromotions` to `false` and `dopunchcards` to `false`. Doing so stops the `too early` error, but generates the current error.

I am using the v1.2.5 release (I had used the pre-release via git pull earlier, but went back to the 'stable' release)

```
[11/28/2023, 7:15:16 PM] [PID: x] [LOG] [SEARCH-BING] Starting bing searches
/root/Microsoft-Rewards-Script-main/dist/functions/activities/Search.js:21
            (edgeData.pointProgressMax - edgeData.pointProgress) + (genericData.pointProgressMax - genericData.pointProgress);
                      ^

TypeError: Cannot read properties of undefined (reading 'pointProgressMax')
    at Search.doSearch (/root/Microsoft-Rewards-Script-main/dist/functions/activities/Search.js:21:23)
    at Activities.doSearch (/root/Microsoft-Rewards-Script-main/dist/functions/Activities.js:13:26)
    at MicrosoftRewardsBot.Desktop (/root/Microsoft-Rewards-Script-main/dist/index.js:139:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MicrosoftRewardsBot.runTasks (/root/Microsoft-Rewards-Script-main/dist/index.js:82:13)

Node.js v20.10.0
```

**Comment by TheNetsky** [comment]
Try 1.3.0, reopen or comment with info if the issue is still present.
