### ISSUE TITLE
Error: Requesting main frame too early!

### ISSUE THREAD

**Issue by tntran10** [TheNetsky/Microsoft-Rewards-Script#3]
I seem to be getting this error when running the script and it'll timeout. Any thoughts on solving this?

**Comment by tntran10** [comment]
This is what I'm seeing when the script crashes.

> microsoft-rewards-script@1.2.0 start
> node ./dist/index.js

[2023-10-16T19:19:11.833Z] [PID: 25108] [LOG] [MAIN] Bot started with 1 clusters
[2023-10-16T19:19:11.834Z] [PID: 25108] [LOG] [MAIN-WORKER] Started tasks for account sam123456789088-mail@yahoo.com
[2023-10-16T19:19:13.082Z] [PID: 25108] [LOG] [MAIN] Starting DESKTOP browser
[2023-10-16T19:19:15.244Z] [PID: 25108] [LOG] [LOGIN] Already logged in
[2023-10-16T19:19:15.244Z] [PID: 25108] [LOG] [LOGIN-BING] Verifying Bing login
[2023-10-16T19:19:19.797Z] [PID: 25108] [LOG] [LOGIN-BING] Bing login verification passed!
[2023-10-16T19:19:19.797Z] [PID: 25108] [LOG] [LOGIN] Logged in successfully
[2023-10-16T19:19:29.105Z] [PID: 25108] [LOG] [MAIN-POINTS] Current point count: 7795
[2023-10-16T19:19:29.105Z] [PID: 25108] [LOG] [MAIN-POINTS] You can earn 250 points today
[2023-10-16T19:19:29.106Z] [PID: 25108] [LOG] [DAILY-SET] All Daily Set" items have already been completed
[2023-10-16T19:19:29.106Z] [PID: 25108] [LOG] [MORE-PROMOTIONS] Started solving "More Promotions" item
[2023-10-16T19:19:29.685Z] [PID: 25108] [LOG] [ACTIVITY] Found activity type: "UrlReward" title: "Did you know…"
[2023-10-16T19:19:29.685Z] [PID: 25108] [LOG] [URL-REWARD] Trying to complete UrlReward
[2023-10-16T19:19:39.699Z] [PID: 25108] [ERROR] [URL-REWARD] An error occurred:TimeoutError: Timed out after waiting 10000ms
[2023-10-16T19:19:41.202Z] [PID: 25108] [ERROR] [ACTIVITY] An error occurred:Error: Requesting main frame too early!
[2023-10-16T19:19:41.202Z] [PID: 25108] [ERROR] [ACTIVITY] An error occurred:Error: Requesting main frame too early!
[2023-10-16T19:19:41.202Z] [PID: 25108] [ERROR] [ACTIVITY] An error occurred:Error: Requesting main frame too early!
[2023-10-16T19:19:41.202Z] [PID: 25108] [ERROR] [ACTIVITY] An error occurred:Error: Requesting main frame too early!
[2023-10-16T19:19:41.202Z] [PID: 25108] [ERROR] [ACTIVITY] An error occurred:Error: Requesting main frame too early!
[2023-10-16T19:19:41.202Z] [PID: 25108] [LOG] [MORE-PROMOTIONS] All "More Promotion" items have been completed
[2023-10-16T19:19:41.202Z] [PID: 25108] [LOG] [PUNCH-CARD] Started solving "Punch Card" items for punchcard: "Trick or treat!"
[2023-10-16T19:19:42.553Z] [PID: 25108] [LOG] [ACTIVITY] Found activity type: "UrlReward" title: "Great minds think alike"
[2023-10-16T19:19:42.554Z] [PID: 25108] [LOG] [URL-REWARD] Trying to complete UrlReward
[2023-10-16T19:19:45.602Z] [PID: 25108] [LOG] [URL-REWARD] Completed the UrlReward successfully
[2023-10-16T19:19:47.661Z] [PID: 25108] [LOG] [ACTIVITY] Found activity type: "UrlReward" title: "Ghastly gourmet party grub"
[2023-10-16T19:19:47.661Z] [PID: 25108] [LOG] [URL-REWARD] Trying to complete UrlReward
[2023-10-16T19:19:50.926Z] [PID: 25108] [LOG] [URL-REWARD] Completed the UrlReward successfully
[2023-10-16T19:19:52.980Z] [PID: 25108] [LOG] [ACTIVITY] Found activity type: "UrlReward" title: "Canine costumes—togs for dogs"
[2023-10-16T19:19:52.980Z] [PID: 25108] [LOG] [URL-REWARD] Trying to complete UrlReward
[2023-10-16T19:19:55.513Z] [PID: 25108] [LOG] [URL-REWARD] Completed the UrlReward successfully
[2023-10-16T19:19:57.572Z] [PID: 25108] [LOG] [ACTIVITY] Found activity type: "UrlReward" title: "Help! I need a wicked theme for my Halloween party!"
[2023-10-16T19:19:57.572Z] [PID: 25108] [LOG] [URL-REWARD] Trying to complete UrlReward
[2023-10-16T19:20:00.710Z] [PID: 25108] [LOG] [URL-REWARD] Completed the UrlReward successfully
[2023-10-16T19:20:02.230Z] [PID: 25108] [LOG] [PUNCH-CARD] All items for punchcard: "Trick or treat!" have been completed
[2023-10-16T19:20:02.230Z] [PID: 25108] [LOG] [PUNCH-CARD] All "Punch Card" items have been completed
C:\Users\tntra\MicrosoftRewardsScripts\node_modules\puppeteer-core\lib\cjs\puppeteer\util\assert.js:28
        throw new Error(message);
              ^

Error: Requesting main frame too early!
    at assert (C:\Users\tntra\MicrosoftRewardsScripts\node_modules\puppeteer-core\lib\cjs\puppeteer\util\assert.js:28:15)
    at FrameManager.mainFrame (C:\Users\tntra\MicrosoftRewardsScripts\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\FrameManager.js:219:32)
    at CdpPage.mainFrame (C:\Users\tntra\MicrosoftRewardsScripts\node_modules\puppeteer-core\lib\cjs\puppeteer\cdp\Page.js:411:35)
    at CdpPage.evaluate (C:\Users\tntra\MicrosoftRewardsScripts\node_modules\puppeteer-core\lib\cjs\puppeteer\api\Page.js:872:31)
    at doSearch (C:\Users\tntra\MicrosoftRewardsScripts\dist\functions\activities\Search.js:14:31)
    at MicrosoftRewardsBot.Desktop (C:\Users\tntra\MicrosoftRewardsScripts\dist\index.js:120:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MicrosoftRewardsBot.runTasks (C:\Users\tntra\MicrosoftRewardsScripts\dist\index.js:71:13)

**Comment by TheNetsky** [comment]
Interesting, is your internet spotty/slow perhaps?

**Comment by tntran10** [comment]
Not that I know of. I stream 4k content just fine with no lag. The error log makes me feel like there is a particular bonus for bing reward that the script is not accounting for.

**Comment by tntran10** [comment]
After messing around, I think I found what's causing the script to time out. It's one of the rewards cards. After I manually, complete it, everything seems to be running fine. I've posted a screenshot of it below in case anyone else runs into this issue.

https://pasteboard.co/rRb5iND9cQSo.png

**Comment by TheNetsky** [comment]
That indeed can be the cause, you shouldn't mess with the window. You can also enable "headless" to disable the window.
