### ISSUE TITLE
NPM issue

### ISSUE THREAD

**Issue by JumpIn-Git** [TheNetsky/Microsoft-Rewards-Script#47]
So I did everything u told us in the explanation, but I got this error, btw do I clone this or download the latest release?
(And yes I did do npm i)

npm run build 

> microsoft-rewards-script@1.4.2 build
> tsc

/home/yaasir/Downloads/Microsoft-Rewards-Script-main/node_modules/typescript/lib/tsc.js:93
  for (let i = startIndex ?? 0; i < array.length; i++) {
                           ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/yaasir/Downloads/Microsoft-Rewards-Script-main/node_modules/typescript/bin/tsc:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by TheNetsky** [comment]
Update your node version.
