### ISSUE TITLE
punchcard

### ISSUE THREAD

**Issue by kirbyosio** [TheNetsky/Microsoft-Rewards-Script#48]
did npm i already 

got this error after "More Promotions"

C:\Users\Curtis\Downloads\Microsoft-Rewards-Script-main\Microsoft-Rewards-Script-main\dist\functions\Workers.js:26
        const punchCardsUncompleted = data.punchCards?.filter(x => !x.parentPromotion.complete) ?? []; // Only return uncompleted punch cards
                                                                                      ^

TypeError: Cannot read properties of null (reading 'complete')
    at C:\Users\Curtis\Downloads\Microsoft-Rewards-Script-main\Microsoft-Rewards-Script-main\dist\functions\Workers.js:26:87
    at Array.filter (<anonymous>)
    at Workers.doPunchCard (C:\Users\Curtis\Downloads\Microsoft-Rewards-Script-main\Microsoft-Rewards-Script-main\dist\functions\Workers.js:26:56)
    at MicrosoftRewardsBot.Desktop (C:\Users\Curtis\Downloads\Microsoft-Rewards-Script-main\Microsoft-Rewards-Script-main\dist\index.js:129:32)
    at async MicrosoftRewardsBot.runTasks (C:\Users\Curtis\Downloads\Microsoft-Rewards-Script-main\Microsoft-Rewards-Script-main\dist\index.js:83:13)

**Comment by TheNetsky** [comment]
Disable promotions for now.
