### ISSUE TITLE
Still a error?

### ISSUE THREAD

**Issue by JumpIn-Git** [TheNetsky/Microsoft-Rewards-Script#51]
I know I have already asked about a error before and im very sorry. I updated to the stable NPM version. I did again everything you told me. I can now login to the account but then after a few seconds it just crashed (Terminal, Linux) 

npm run start

> microsoft-rewards-script@1.4.3 start
> node ./dist/index.js

[1/20/2024, 9:38:45 PM] [PID: 10763] [LOG] [MAIN] Bot started with 1 clusters
[1/20/2024, 9:38:45 PM] [PID: 10763] [LOG] [MAIN-WORKER] Started tasks for account superskateboarder@outlook.com
[1/20/2024, 9:38:46 PM] [PID: 10763] [LOG] [BROWSER] Created browser with User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
[1/20/2024, 9:38:46 PM] [PID: 10763] [LOG] [MAIN] Starting DESKTOP browser
[1/20/2024, 9:39:18 PM] [PID: 10763] [ERROR] [LOGIN] An error occurred:TimeoutError: page.waitForSelector: Timeout 10000ms exceeded.
Call log:
  - waiting for locator('#loginHeader') to be visible

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

**Comment by TheNetsky** [comment]
Try disabling headless and see what the script is doing.

**Comment by JumpIn-Git** [comment]
> .

Ah ok, I will try that.

**Comment by JumpIn-Git** [comment]
> Try disabling headless and see what the script is doing.

Wait headlesss is already disabled by default right?

**Comment by JumpIn-Git** [comment]
> Try disabling headless and see what the script is doing.

Ok so headless is disabled by default so i turned it on and this is the result



npm run start

> microsoft-rewards-script@1.4.3 start
> node ./dist/index.js

[1/21/2024, 8:52:38 AM] [PID: 13703] [LOG] [MAIN] Bot started with 1 clusters
[1/21/2024, 8:52:38 AM] [PID: 13703] [LOG] [MAIN-WORKER] Started tasks for account superskateboarder@outlook.com
[1/21/2024, 8:52:39 AM] [PID: 13703] [LOG] [BROWSER] Created browser with User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Edg/119.0.0.0"
[1/21/2024, 8:52:39 AM] [PID: 13703] [LOG] [MAIN] Starting DESKTOP browser


[1/21/2024, 8:53:03 AM] [PID: 13703] [LOG] [LOGIN] Email entered successfully
[1/21/2024, 8:53:06 AM] [PID: 13703] [LOG] [LOGIN] Password entered successfully
[1/21/2024, 8:53:17 AM] [PID: 13703] [LOG] [LOGIN] Logged into Microsoft successfully
[1/21/2024, 8:53:17 AM] [PID: 13703] [LOG] [LOGIN-BING] Verifying Bing login
[1/21/2024, 8:53:21 AM] [PID: 13703] [LOG] [LOGIN-BING] Bing login verification passed!
[1/21/2024, 8:53:21 AM] [PID: 13703] [LOG] [LOGIN] Logged in successfully
[1/21/2024, 8:53:29 AM] [PID: 13703] [LOG] [GO-HOME] Visited homepage successfully
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.evaluate: TypeError: Cannot read properties of undefined (reading 'log')
    at eval (eval at evaluate (:226:30), <anonymous>:8:32)
    at UtilityScript.evaluate (<anonymous>:228:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at BrowserFunc.getDashboardData (/home/yaasir/Downloads/Microsoft-Rewards-Script-main/dist/browser/BrowserFunc.js:70:55)
    at async MicrosoftRewardsBot.Desktop (/home/yaasir/Downloads/Microsoft-Rewards-Script-main/dist/index.js:105:22)
    at async MicrosoftRewardsBot.runTasks (/home/yaasir/Downloads/Microsoft-Rewards-Script-main/dist/index.js:83:13)

Node.js v20.11.0

**Comment by TheNetsky** [comment]
That's not what I meant. I meant that with headless disabled you can see the browser window. In the window see where or why it gets stuck.

**Comment by JumpIn-Git** [comment]
> That's not what I meant. I meant that with headless disabled you can see the browser window. In the window see where or why it gets stuck.

ah ok. So when i see the browser i manually login and then see the microsoft rewards main page. thats it and and after a few seconds the code just crashes

**Comment by TheNetsky** [comment]
Issue still persisting?

**Comment by TheNetsky** [comment]
Try recording the browser window,

**Comment by JumpIn-Git** [comment]
> Try recording the browser window,

Only thing that happens is I login and it shows bing rewards main page there is no error in the browser

**Comment by TheNetsky** [comment]
I'm unable to replicate this. Maybe someone else can.

**Comment by JumpIn-Git** [comment]
> I'm unable to replicate this. Maybe someone else can.

I will record it later today

**Comment by JumpIn-Git** [comment]
> Try recording the browser window,

ok ill just give up man i broke networkmanager and now i cant use linux and windows doesnt install the packages with npm i

**Comment by TheNetsky** [comment]
Noting more I can do that,  maybe try an alternative script.
