### ISSUE TITLE
browser not found? i'm on mac os sonoma

### ISSUE THREAD

**Issue by itslemcy** [TheNetsky/Microsoft-Rewards-Script#60]
hi!
i'm having this error thrown out:

 npm run start

> microsoft-rewards-script@1.4.4 start
> node ./dist/index.js

[2/7/2024, 7:55:28 PM] [PID: 71499] [LOG] [MAIN] Bot started with 1 clusters
[2/7/2024, 7:55:28 PM] [PID: 71499] [LOG] [MAIN-WORKER] Started tasks for account USR@gmail.com
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

browserType.launch: Executable doesn't exist at /Users/USR/Library/Caches/ms-playwright/chromium-1097/chrome-mac/Chromium.app/Contents/MacOS/Chromium
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at Browser.createBrowser (/Users/USR/Desktop/Microsoft-Rewards-Script-main/dist/browser/Browser.js:20:61)
    at MicrosoftRewardsBot.Desktop (/Users/USR/Desktop/Microsoft-Rewards-Script-main/dist/index.js:99:51)
    at MicrosoftRewardsBot.runTasks (/Users/USR/Desktop/Microsoft-Rewards-Script-main/dist/index.js:83:24)
    at MicrosoftRewardsBot.run (/Users/USR/Desktop/Microsoft-Rewards-Script-main/dist/index.js:51:18)
    at /Users/USR/Desktop/Microsoft-Rewards-Script-main/dist/index.js:197:9 {
  name: 'Error'
}

Node.js v21.6.1

**Comment by itslemcy** [comment]
i'm an idiot, sorry
