### ISSUE TITLE
Crash at certain step

### ISSUE THREAD

**Issue by iFredOS** [TheNetsky/Microsoft-Rewards-Script#63]
```
[WARN] [SEARCH-BING] Retrying search, attempt 0/5
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goBack: Timeout 30000ms exceeded.
Call log:
  - waiting for navigation until "load"

    at Search.closeTabs (/usr/src/microsoft-rewards-script/dist/functions/activities/Search.js:256:27)
    at Search.bingSearch (/usr/src/microsoft-rewards-script/dist/functions/activities/Search.js:145:28)
    at async Search.doSearch (/usr/src/microsoft-rewards-script/dist/functions/activities/Search.js:39:30)
    at async Activities.doSearch (/usr/src/microsoft-rewards-script/dist/functions/Activities.js:13:13)
    at async MicrosoftRewardsBot.Desktop (/usr/src/microsoft-rewards-script/dist/index.js:134:13)
    at async MicrosoftRewardsBot.runTasks (/usr/src/microsoft-rewards-script/dist/index.js:83:13) {
  name: 'TimeoutError'
}

Node.js v18.19.0
```

**Comment by CasualPlayer96** [comment]
[ERROR] [GO-HOME] An error occurred:TimeoutError: page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://rewards.bing.com", waiting until "load"

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.11.05

**Comment by TheNetsky** [comment]
Both issues seems to related to a timeout, I don't think that's the script's fault. Also those are 2 different errors.
