### ISSUE TITLE
Search having errors

### ISSUE THREAD

**Issue by Kraker01** [TheNetsky/Microsoft-Rewards-Script#91]
Latest version, tried a fresh new install, searches are experiencing problems:
[10/4/2024, 09:47:49] [PID: 3472] [ERROR] [SEARCH-BING] Search failed, An error occurred:TimeoutError: page.waitForSelector: Timeout 10000ms exceeded.
Call log:
  - waiting for locator('#sb_form_q') to be visible

[10/4/2024, 09:43:02] [PID: 3472] [ERROR] [SEARCH-BING] Search failed, An error occurred:TimeoutError: page.click: Timeout 30000ms exceeded.
Call log:
  - waiting for locator('#sb_form_q')
  -   locator resolved to <textarea dir="" name="q" rows="1" value="nasa" type="sear…>nasa</textarea>
  - attempting click action
  -   waiting for element to be visible, enabled and stable
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling
  -   <div class="bnp_overlay_wrapper"></div> from <div class=" " id="bnp.nid.63249" data-vertical="serp…>…</div> subtree intercepts pointer events
  - retrying click action, attempt #1
  -   waiting for element to be visible, enabled and stable
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling

**Comment by TheNetsky** [comment]
Disable headless and look at what the script is doing.

**Comment by Kraker01** [comment]
Keep on loading the page (internet is working fine) and suddendly stops:

[ERROR] [GO-HOME] An error occurred:TimeoutError: page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://rewards.bing.com/", waiting until "load"

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v18.12.1

**Comment by serzak51** [comment]
For the first one check if the cookie page is shown, it messes things up and put errors like these kinds. The points seems to still be registered, but it's extremely slow. But for the second error it also started appearing for me since a few days, at the login. Not really sure what's causing it. I think it might be related to slow internet, as sometimes the page doesn't seems to have finished loading, but i'm not 100% sure.

[12/04/2024 09:10:13] [PID: 8988] [ERROR] [LOGIN] An error occurred:TimeoutError: page.goto: Timeout 30000ms exceeded.
Call log:
  - navigating to "https://rewards.bing.com/signin", waiting until "load"

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v20.11.1

**Comment by SimiJS** [comment]
I am also experiencing similar problems, will provide logs:

```
[4/15/2024, 9:36:10 AM] [PID: 1992049] [ERROR] [SEARCH-BING] Search failed, An error occurred:TimeoutError: page.click: Timeout 30000ms exceeded.
Call log:
  - waiting for locator('#sb_form_q')
  -   locator resolved to <textarea dir="" name="q" rows="1" value="ufc" type="searc…>ufc</textarea>
  - attempting click action
  -   waiting for element to be visible, enabled and stable
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling
  -   <div class="bnp_overlay_wrapper"></div> from <div class=" " id="bnp.nid.63249" data-vertical="serp…>…</div> subtree intercepts pointer events
  - retrying click action, attempt #1
  -   waiting for element to be visible, enabled and stable
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling
  -   <div class="bnp_overlay_wrapper"></div> from <div class=" " id="bnp.nid.63249" data-vertical="serp…>…</div> subtree intercepts pointer events
  - retrying click action, attempt #2
```

---

```
[4/15/2024, 9:36:27 AM] [PID: 1992049] [ERROR] [SEARCH-BING] Search failed, An error occurred:TimeoutError: page.waitForSelector: Timeout 10000ms exceeded.
Call log:
  - waiting for locator('#sb_form_q') to be visible
  -   locator resolved to visible <textarea name="q" rows="1" autofocus="" type="search" id=…></textarea>

[4/15/2024, 9:36:27 AM] [PID: 1992049] [WARN] [SEARCH-BING] Retrying search, attempt 1/5
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goBack: Timeout 30000ms exceeded.
Call log:
  - waiting for navigation until "load"
  -   navigated to "https://rewards.bing.com/"

    at Search.closeTabs (/home/simi/Docker/Compose/JSRewards/dist/functions/activities/Search.js:256:27)
    at Search.bingSearch (/home/simi/Docker/Compose/JSRewards/dist/functions/activities/Search.js:145:28)
    at async Search.doSearch (/home/simi/Docker/Compose/JSRewards/dist/functions/activities/Search.js:39:30)
    at async Activities.doSearch (/home/simi/Docker/Compose/JSRewards/dist/functions/Activities.js:13:13)
    at async MicrosoftRewardsBot.Desktop (/home/simi/Docker/Compose/JSRewards/dist/index.js:134:13)
    at async MicrosoftRewardsBot.runTasks (/home/simi/Docker/Compose/JSRewards/dist/index.js:83:13) {
  name: 'TimeoutError'
}
```
Latest NodeJS v21.7.3

**Comment by psegovias** [comment]
Same problem  over here:

```
[4/17/2024, 10:20:18 AM] [PID: 796] [LOG] [BROWSER] Created browser with User-Agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36 Edg/122.0.0.0"
[4/17/2024, 10:20:19 AM] [PID: 796] [LOG] [MAIN] Starting DESKTOP browser
[4/17/2024, 10:20:30 AM] [PID: 796] [ERROR] [LOGIN] An error occurred:Error: page.goto: net::ERR_HTTP_RESPONSE_CODE_FAILURE at https://rewards.bing.com/signin
Call log:
  - navigating to "https://rewards.bing.com/signin", waiting until "load"

node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
}

Node.js v21.7.2
```

**Comment by TheNetsky** [comment]
Tried https://github.com/TheNetsky/Microsoft-Rewards-Script/issues/93 ?
